package:
  name: zizmor
  version: "1.25.0"
  epoch: 0 # GHSA-82j2-j2ch-gfr8
  description: "A static analysis tool for GitHub Actions"
  copyright:
    - license: MIT
  resources:
    cpu: "13"
    memory: 13Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/woodruffw/zizmor
      expected-commit: ee075979c40cc6b8278bc0215477d03d65c80980
      tag: v${{package.version}}

  - uses: rust/cargobump

  - uses: cargo/build
    with:
      output: ${{package.name}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: woodruffw/zizmor
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ver-check
      with:
        bins: zizmor
    - uses: test/tw/help-check
      with:
        bins: zizmor
